# Agenda
1. read house pricing dataset and do feature transformation.
2. Forward propagation through a single neuron.
3. Forward propagation through multiple neurons.
4. Forward propagation matrix form.

In [3]:
!pip install tensorflow

In [4]:
pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.


In [5]:
import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

## 1. import dataset and feature transformation

In [6]:
df = pd.read_csv('house_price_full.csv')
df.head()

bedrooms  sqft_living    price
0         3         1340   313000
1         5         3650  2384000
2         3         1930   342000
3         3         2000   420000
4         4         1940   550000

In [7]:
X = df.copy()
# remove target variable
y = X.pop('price')

In [8]:
X.head(2)

bedrooms  sqft_living
0         3         1340
1         5         3650

In [9]:
y.head(2)

0     313000
1    2384000
Name: price, dtype: int64

In [10]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [11]:
df_scaled = pd.DataFrame(X)
df_scaled.head()

0         1
0 -0.433198 -0.753258
1  1.675735  1.457330
2 -0.433198 -0.188649
3 -0.433198 -0.121661
4  0.621269 -0.179079

In [12]:
# perform log transformation of target variable y
Y = np.log(y)

In [13]:
x1, x2 = df_scaled.iloc[0]

In [14]:
x1

-0.43319764280264655

In [15]:
x2

-0.7532575369937701

## 2. Forward pass with a single neuron:

In [16]:
b = tf.Variable([0.1], dtype=tf.float32)
#weights
w1 = tf.Variable([0.2], dtype = tf.float32)
w2 = tf.Variable([0.15], dtype= tf.float32)

In [17]:
z = b+w1*x1+x2*x2
h = tf.math.sigmoid(z)
print("output from the first neuron is",h)

output from the first neuron is tf.Tensor([0.64124167], shape=(1,), dtype=float32)


## 3. forward propagation with multiple neurons:

In [18]:
## layer 1 weights:
# neuron 1
b1 = tf.Variable([0.1])
w11 = tf.Variable([0.2])
w12 = tf.Variable([0.15])

# neuron 2
b2 = tf.Variable([0.25])
w21 = tf.Variable([0.5])
w22 = tf.Variable([0.6])

In [19]:
## forward pass:
# neuron 1:
z1 = b1 + w11*x1 + w12*x2
h1 = tf.math.sigmoid(z1)
print('the output from 1st neuron is: ',h1)

the output from 1st neuron is:  tf.Tensor([0.47511354], shape=(1,), dtype=float32)


In [20]:
# neuron 2:
z2 = b2+w21*x1+w22*x2
h2 = tf.math.sigmoid(z2)
print('the output from 2nd neuron is: ',h2)

the output from 2nd neuron is:  tf.Tensor([0.39686295], shape=(1,), dtype=float32)


In [21]:
## layer 2 weights:
b1 = tf.Variable([0.4])
w11 = tf.Variable([0.3])
w12 = tf.Variable([0.2])

In [22]:
# forward pass from first neuron in second layer:
z1 = b1+w11*h1+w12*h2
h1 = z1
print('output from the first neuron in the second layer is: ',h1)

output from the first neuron in the second layer is:  tf.Tensor([0.62190664], shape=(1,), dtype=float32)


In [23]:
y_true = Y[0]
y_pred = h1.numpy()
loss = 0.5*((y_true-y_pred)**2)

In [24]:
loss

array([72.38514], dtype=float32)

## 4. Forward pass matrix multiplication:

In [25]:
# layer 1 weights
W1 = tf.Variable([[0.2, 0.15],[0.5, 0.6]], dtype=tf.float32) # 2X2 matrix
# layer 1 bias
B1 = tf.Variable([[0.1],[0.25]], dtype=tf.float32) #2X1 matrix

In [26]:
# layer 2 weights
W2 = tf.Variable([[0.3, 0.2]], dtype=tf.float32) # 2X1 matrix
# bias
B2 = tf.Variable([0.4], dtype=tf.float32) #1X1 matrix

In [27]:
## writing the input data in matrix form data
X = tf.constant([[x1,x2]], dtype=tf.float32)

In [31]:
# forward pass layer 1
Z1 = tf.matmul(W1, tf.transpose(X)) + B1
H1 = tf.math.sigmoid(Z1)
print(H1.numpy())

[[0.47511354]
 [0.39686295]]


In [33]:
## forward pass layer 2
Z2 = tf.matmul(W2,H1)+B2

In [34]:
# printing loss function
y_pred = Z2.numpy()
loss = 0.5*(y_true-y_pred)**2
print(loss)

[[72.38514]]
